server.port=8080
server.protocol=TCP
server.maxConnections=10
db.url=jdbc:mysql://localhost:3306/messaging_system?createDatabaseIfNotExist=true
db.user=messaging_app
db.password=messaging_app
storage.originalDir=uploads/original
storage.encryptedDir=uploads/encrypted